### ISSUE TITLE
Principe OOCSS ?

### ISSUE THREAD

**Issue by kaelig** [Cerdic/Z#2]
Je remarque que les div du layout sont nommées par des ID dans body.php.

Comme tu sembles promouvoir la technique de Nicole Sullivan, il serait peut-être plus cohérent de l'implémenter directement dans Z en changeant ces ID en classes.

**Comment by Cerdic** [comment]
En fait le framework ne fait aucun choix concernant l'utilisation d'id ou de classes sur le layout. Mais il est vrai que la demo utilise des id par comodité. Tu peux changer pour des classes si tu préfères, pas de soucis pour moi.
